"""empty message

Revision ID: d0c8a355b381
Revises: a2ff7d83c09d
Create Date: 2020-04-06 12:58:56.952237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c8a355b381'
down_revision = 'a2ff7d83c09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('declaration_suspect', sa.Column('descriptif', sa.Text(), nullable=True))
    op.add_column('don', sa.Column('descriptif', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('don', 'descriptif')
    op.drop_column('declaration_suspect', 'descriptif')
    # ### end Alembic commands ###
